apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
    type: front-end
    use: apd
spec:
  containers:
    - name: httpd-container
      image: a11aruna/phphttpd-hostname

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: app
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      use: apd
  template:
    metadata:
      name: app-pod
      labels:
        app: app
        type: front-end
        use: apd
    spec:  # This was missing in the original YAML
      containers:
        - name: httpd-container
          image: a11aruna/phphttpd-hostname    

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 #httpd container port
      port: 80 #port which service opens
      nodePort: 30008
  selector:
    use: apd


