apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-webserver-deployment
  labels:
    app: app-webserver
    type: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-webserver
  template:

    metadata:
      name: webserver
      labels:
        app: app-webserver
        type: web-server
        use: system-web-server
    spec:  # This was missing in the original YAML
      containers:
        - name: httpd-webserver
          image: a11aruna/php-httpd
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webserver-np-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 #httpd container port
      port: 81 #port which service opens
      nodePort: 30008
  selector:
    app: app-webserver
