apiVersion: v1
kind: Service
metadata:
  name: mongodb-internal-service
  namespace: ns-apd #add name space
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
