FROM php:apache
LABEL Author="Aruna" Description="A comprehensive docker image to run php:apache"
EXPOSE 80
WORKDIR /var/www/html
RUN wget https://raw.githubusercontent.com/ifsemail9/k8s/main/sample-project/php-info.php

