apiVersion: v1
kind: Service
metadata:
  name: mongo-express-external-service
  namespace: ns-apd #add name space
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30333
#nodePort should be between 30000 - 32767
