FROM haproxy
LABEL author="Aruna" description="A comprehensive docker image to run php:apache"

# Expose web ports
EXPOSE 80 443

# copy index file to WORKDIR
COPY haproxy.cfg /usr/local/etc/haproxy/
